import { promises as fs } from 'fs';
import path from 'path';

const WEEKLY_PLAN_FILE = '/Users/mia/.openclaw/workspace/tasks/weekly/plan.md';
const WEEKLY_ARCHIVED_DIR = '/Users/mia/.openclaw/workspace/tasks/weekly/archived';

// Parse weekly plan
function parseWeeklyPlan(content) {
  const tasks = [];
  const lines = content.split('\n');
  let inPlanSection = false;

  for (const line of lines) {
    if (line.startsWith('# 📅 Weekly Plan')) {
      inPlanSection = true;
      continue;
    }

    if (line.startsWith('##')) {
      inPlanSection = false;
    }

    if (inPlanSection && line.startsWith('- [') && !line.includes('*(This file') && !line.includes('*(此文件')) {
      const idMatch = line.match(/\[#([a-zA-Z0-9_-]+)\]/);
      const id = idMatch ? idMatch[1] : Date.now().toString();
      const text = line.replace(/^- \[[ x]\] \[#([a-zA-Z0-9_-]+)\] /, '').trim();
      const isDone = line.includes('- [x]');
      tasks.push({ id, text, done: isDone });
    }
  }

  return tasks;
}

// Append to weekly plan
function appendToWeeklyPlan(content, text) {
  const id = Date.now().toString();
  const newTask = `- [ ] [#${id}] ${text}`;

  const lines = content.split('\n');
  const insertionIndex = lines.findIndex(line => line.startsWith('##'));
  const insertAt = insertionIndex === -1 ? lines.length : insertionIndex;

  lines.splice(insertAt, 0, newTask);
  return lines.join('\n');
}

// Generate weekly plan template
function generateWeeklyPlanTemplate(text) {
  const id = Date.now().toString();
  return `# 📅 Weekly Plan

*(This file is automatically generated by Weekly Check)*

- [ ] [#${id}] ${text}
`;
}

// GET - Fetch weekly plan
export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const date = searchParams.get('date'); // For viewing archived weeks

  if (date) {
    // Fetch archived week
    const archiveFile = path.join(WEEKLY_ARCHIVED_DIR, date, 'plan.md');
    try {
      const content = await fs.readFile(archiveFile, 'utf-8');
      const tasks = parseWeeklyPlan(content);
      return Response.json({ tasks, date, archived: true });
    } catch (error) {
      return Response.json({ error: 'Week not found' }, { status: 404 });
    }
  }

  // Fetch current weekly plan
  try {
    const content = await fs.readFile(WEEKLY_PLAN_FILE, 'utf-8');
    const tasks = parseWeeklyPlan(content);
    return Response.json({ tasks });
  } catch (error) {
    // File doesn't exist
    return Response.json({ tasks: [] });
  }
}

// POST - Add task to weekly plan
export async function POST(request) {
  const { text } = await request.json();

  try {
    const content = await fs.readFile(WEEKLY_PLAN_FILE, 'utf-8');
    const newContent = appendToWeeklyPlan(content, text);
    await fs.writeFile(WEEKLY_PLAN_FILE, newContent);
    return Response.json({ success: true });
  } catch (error) {
    const newContent = generateWeeklyPlanTemplate(text);
    await fs.writeFile(WEEKLY_PLAN_FILE, newContent);
    return Response.json({ success: true });
  }
}

// PUT - Toggle task status in weekly plan
export async function PUT(request) {
  const { taskId } = await request.json();

  try {
    const content = await fs.readFile(WEEKLY_PLAN_FILE, 'utf-8');
    const lines = content.split('\n');
    let updated = false;

    for (let i = 0; i < lines.length; i++) {
      if (lines[i].includes(`[#${taskId}]`)) {
        lines[i] = lines[i].replace(/^- \[([ x])\]/, (match, checked) => {
          return `- [${checked === 'x' ? ' ' : 'x'}]`;
        });
        updated = true;
        break;
      }
    }

    if (updated) {
      await fs.writeFile(WEEKLY_PLAN_FILE, lines.join('\n'));
      return Response.json({ success: true });
    }

    return Response.json({ success: false, error: 'Task not found' }, { status: 404 });
  } catch (error) {
    return Response.json({ success: false, error: 'Failed to update task' }, { status: 500 });
  }
}

// DELETE - Remove task from weekly plan
export async function DELETE(request) {
  const { searchParams } = new URL(request.url);
  const taskId = searchParams.get('taskId');

  try {
    const content = await fs.readFile(WEEKLY_PLAN_FILE, 'utf-8');
    const lines = content.filter(line => !line.includes(`[#${taskId}]`));
    await fs.writeFile(WEEKLY_PLAN_FILE, lines.join('\n'));
    return Response.json({ success: true });
  } catch (error) {
    return Response.json({ success: false, error: 'Failed to delete task' }, { status: 500 });
  }
}
